# Generated by Django 5.1.1 on 2024-10-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_id', models.CharField(max_length=100, unique=True)),
                ('espn_name', models.CharField(max_length=100)),
                ('yahoo_player_id', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('espn_link', models.URLField()),
                ('yahoo_link', models.URLField()),
            ],
        ),
    ]
